# Generated by Django 4.0.4 on 2022-05-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanofficer_name', models.TextField(blank=True, null=True)),
                ('employee', models.TextField(blank=True, null=True)),
                ('timeadd', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'choose',
                'managed': False,
            },
        ),
    ]
