# Generated by Django 4.0.4 on 2022-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0002_choose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose',
            options={},
        ),
    ]
