# Generated by Django 4.0.4 on 2022-05-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0004_alter_choose_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choose',
        ),
    ]
