# Generated by Django 4.0.4 on 2022-05-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0008_choose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose',
            options={'managed': False},
        ),
    ]
