# Generated by Django 4.0.4 on 2022-05-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0009_alter_choose_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choose',
            table='choose',
        ),
    ]
