# Generated by Django 4.0.4 on 2022-05-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0010_alter_choose_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choose',
            table='teamleader_choose',
        ),
    ]
