# Generated by Django 4.0.4 on 2022-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0011_alter_choose_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('timeadd', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
