# Generated by Django 4.0.4 on 2022-05-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0012_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose',
            options={},
        ),
    ]
