# Generated by Django 4.0.4 on 2022-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0013_alter_choose_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='loanofficer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='choose',
            table=None,
        ),
    ]
