# Generated by Django 4.0.4 on 2022-05-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0014_alter_choose_loanofficer_name_alter_choose_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose',
            options={'managed': False},
        ),
    ]
