# Generated by Django 4.0.4 on 2022-05-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0018_alter_choose_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choose',
            table='teamleader_choose',
        ),
    ]
